name: setup / download-zip

on:
  workflow_call:
    inputs:
      zip_url:
        required: true
        type: string
      version:
        required: true
        type: string
    outputs:
      app_name:
        value: ${{ jobs.download-zip.outputs.app_name }}
      exe_name:
        value: ${{ jobs.download-zip.outputs.exe_name }}

jobs:
  download-zip:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.set-outputs.outputs.app_name }}
      exe_name: ${{ steps.set-outputs.outputs.exe_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup config from repository
        run: |
          mkdir -p extracted
          echo '{"api_server": "http://remotedesk.hglk.link:21114", "id_server": "remotedesk.hglk.link", "relay_server": "remotedesk.hglk.link", "key": "LyAnbMUs2DAvCngHCVn8rIXXr48L8bBlSK8xgypAzek=", "app_name": "HostGrap Remote Support", "exe_name": "HostGrap-Support", "icon": ""}' > extracted/config.json
          echo "Default config created."

      - name: Set outputs
        id: set-outputs
        run: |
          APP_NAME=$(python3 -c "import json; print(json.load(open('extracted/config.json'))['app_name'])")
          EXE_NAME=$(python3 -c "import json; print(json.load(open('extracted/config.json'))['exe_name'])")
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "exe_name=$EXE_NAME" >> $GITHUB_OUTPUT

      - name: Upload configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets_b929ae02-afb2-4ab2-a26a-8fc0ffd0bfef.zip
          path: extracted/
